apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: innabox

resources:
  - ../../base

patches:
  - patch: |
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: fulfillment-api
      spec:
        issuerRef:
          name: letsencrypt-production-dns01
          kind: ClusterIssuer
        duration: 2160h0m0s
        renewBefore: 360h0m0s
        dnsNames:
          - fulfillment-api.apps.hypershift1.nerc.mghpcc.org
